#%RAML 1.0 Library
annotationTypes:
  oas-schema-title:
    type: string
    allowedTargets: TypeDeclaration
  oas-body-name:
    type: string
    allowedTargets: TypeDeclaration
  oas-summary:
    type: string
    allowedTargets: Method
  oas-tags:
    type: 'string[]'
    allowedTargets: Method  
types:
  simpleService:
    type: object
    properties:
      id:
        type: integer
        format: int64
        required: false
      href:
        type: string
        required: false
      name:
        type: string
        required: false
      description:
        type: string
        required: false
      type:
        type: string
        required: false
      version:
        type: string
        required: false
      state:
        type: string
        enum:
          - Inactive
          - Active
          - Terminated
        required: false
  service:
    type: simpleService
    properties:
      serviceSpecification:
        type: ServiceSpecification
        required: false
      serviceCharacteristic:
        type: array
        items:
          type: ServiceCharacteristic
      serviceRelationship:
        type: array
        items:
          type: ServiceRelationship
        required: false
      relatedParty:
        type: array
        items:
          type: RelatedParty
        required: false
      supportingService:
        type: array
        items:
          type: SupportingService
        required: false
      supportingResource:
        type: array
        items:
          type: SupportingResource
        required: false
  request:
    type: object
    properties:
      method:
        type: string
        required: false
      to:
        type: string
        required: false
      body:
        type: string
      header:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            value:
              type: string
          additionalProperties: false
        (oas-schema-title): header
    additionalProperties: false
  response:
    type: object
    properties:
      statusCode:
        type: string
        required: false
      body:
        type: string
      header:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            value:
              type: string
          additionalProperties: false
        (oas-schema-title): header
    additionalProperties: false
  monitor:
    description: 'JSON Schema generated by XMLSpy v2016 rel. 2 (http://www.altova.com)'
    type: object
    properties:
      id:
        type: string
      type:
        type: string
        required: false
      state:
        type: string
      request:
        type: request
      response:
        type: response
      href:
        type: string
      sourceHref:
        type: string
    additionalProperties: false
  resource:
    type: object
    properties:
      id:
        type: integer
        format: int64
      href:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: string
      version:
        type: string
      adminState:
        type: string
        enum:
          - unknown
          - locked
          - shuttingDown
          - unlocked
      operationalState:
        type: string
        enum:
          - unknown
          - disabled
          - enabled
          - testing
      usageState:
        type: string
        enum:
          - unknown
          - idle
          - active
          - busy
      state:
        type: string
        enum:
          - inactive
          - active
          - terminated
      resourceSpecification:
        type: ResourceSpecification
      resourceCharacteristic:
        type: array
        items:
          type: ResourceCharacteristic
      resourceRelationship:
        type: array
        items:
          type: ResourceRelationship
      relatedParty:
        type: array
        items:
          type: RelatedParty
  ServiceSpecification:
    type: object
    properties:
      id:
        type: string
      href:
        type: string
  ResourceSpecification:
    type: object
    properties:
      id:
        type: string
      href:
        type: string
  SupportingResource:
    type: object
    properties:
      id:
        type: string
      href:
        type: string
  SupportingService:
    type: object
    properties:
      id:
        type: string
      href:
        type: string
  NetworkFuction:
    type: object
    properties:
      id:
        type: string
      href:
        type: string
  ServiceRelationship:
    type: object
    properties:
      type:
        type: string
        required: false
      service:
        type: ServiceRef
  ResourceRelationship:
    type: object
    properties:
      type:
        type: string
        required: false
      resource:
        type: ResourceRef
  ServiceRef:
    type: object
    properties:
      id:
        type: string
      href:
        type: string
  ResourceRef:
    type: object
    properties:
      id:
        type: string
      href:
        type: string
  ServiceCharacteristic:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
  ResourceCharacteristic:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
  RelatedParty:
    type: object
    properties:
      id:
        type: string
      role:
        type: string
      href:
        type: string
  Hub:
    type: object
    properties:
      id:
        type: string
      callback:
        type: string
      query:
        type: string
  NewHub:
    type: object
    properties:
      id:
        type: string
        required: false
      callback:
        type: string
      query:
        type: string
        required: false